services:

  myapp:
      image: 'docker.io/library/jetbrains-exposed-orm:0.0.1-SNAPSHOT'
      ports:
      - '8080:8080'
      depends_on:
      - postgres

  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
